<a href="https://colab.research.google.com/github/jaingautam93/Python_Pytorch_GTM/blob/master/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Torch Tensor Functions

### Top Five Torch Tensor Operations

Pytorch is free and open-source machine learning library based on python, based on torch, built to provide flexibility as a deep learning development platform.

Let's check out some of the functions that operate on tensors.

In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.tensor: reshape

The reshape function takes an input tensor and returns a tensor with same data and number of elements but in a specified shape

input: A tensor to be reshaped

shape: The new shape in for of python tuple(Shape must bve compatible with the number of data)

In [3]:
# Example 1 - working
data=torch.randn(size=[2,4])
print(data)
torch.reshape(input=data, shape=(4,2))

tensor([[-0.5639,  2.5635,  1.1584,  0.4433],
        [-2.2768, -0.0283,  0.3005, -2.5065]])


tensor([[-0.5639,  2.5635],
        [ 1.1584,  0.4433],
        [-2.2768, -0.0283],
        [ 0.3005, -2.5065]])

The Input tensor was of shape (2,4) and output is (4,2).

In [4]:
# Example 2 - working
torch.reshape(input=torch.randn((3,4)), shape=(6,2))

tensor([[-0.1104, -0.9607],
        [-0.1917,  1.9993],
        [-1.2721, -1.6472],
        [ 0.0060,  0.8191],
        [ 0.5472, -0.3843],
        [ 0.3364,  1.0022]])

Here the input shape is (3,4) but the output is (6,2) not(4,3). This can be done until we maintain the dimensionality of the tensor and make sure the number of elements in output tensor is same as that of input tensor.

In [5]:
# Example 3 - breaking (to illustrate when it breaks)
torch.reshape(input=data, shape=(3,3))

RuntimeError: ignored

Here the reshape function breaks as the dimension/shape of input is (2,4) i.e., 8 elements but the reshape size is (3,3) i.e., 9 elements.

The reshape function can be used during matrix mutiplication or resizing the tensor for creating new neural nets.

## Function 2 - torch.tensor:backward
It compute the gradient of a current tensor w.r.t graph leaves. It accumulates the gradient in the leaves which should be zeroed before calling them.

torch.backward(gradient=None, retain_graph=None, create_graph=False)


In [11]:
# Example 1 - working
data = torch.tensor([3.,4,5], requires_grad=True)
data


tensor([3., 4., 5.], requires_grad=True)

In [13]:
new_data = data.pow(4).sum()
new_data


tensor(962., grad_fn=<SumBackward0>)

In [0]:
new_data.backward()

In [15]:
data.grad

tensor([108., 256., 500.])

In [16]:
data.pow(4)

tensor([ 81., 256., 625.], grad_fn=<PowBackward0>)

f(x) = x^4

Derivative: f'(x) = (d/dx)f(x)

f'(x) = 4*(x^3)
For x=3:

f(x) = x^4 = 3^4 = 81

f'(x)=4x^3 = 43^3 = 108

In [17]:
# Example 2 - working
data2 = torch.tensor(54321.,requires_grad=True)
data2

tensor(54321., requires_grad=True)

In [18]:
data2.backward()
data2.grad

tensor(1.)

Tensor backward function also works on scalar value but needs gradient funtion to perform this.

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
data3=torch.tensor(54321.)
data3

tensor(54321.)

In [20]:
data3.backward()

RuntimeError: ignored

Here the backward function fails because data3 does not know about the gradient function to do the derivative of the given constant.

Backward function is used to determine the gradient of the loss function w.r.t all other variables and its output will always be a scalar.

## Function 3 - torch.tensor: var

The var function returns the variance of all the elements present in the tensor. If unbiased= False, then variance is calculated via biased estimator.

var(dim=None, unbiased=True, keepdim=False) → Tensor


In [21]:
# Example 1 - working
data = torch.tensor([1.,9,5,4,1,7,3,7,5,6])
data.var()

tensor(6.8444)

Variance of the input is always floating point.

In [24]:
# Example 2 - working
data=torch.randn(size=[3,5])
data.var()

tensor(1.1549)

Variance can be found of any dimension tensor.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
data = torch.tensor([1,9,5,4,1,7,3,7,5,6])
data.var()

RuntimeError: ignored

This function breaks here because the input passed is of 'integer' datatype instead of 'floating point'. The variance will be of float type so input should be of floating type.

This function should be used calculate the variance which is an error in model's sensitivity to small fluctuation in the training set.

## Function 4 - torch.tensor: abs

It calculates the absolute value of a given tensor element-wise.

input: The input tensor

out: The tensor to which the output would be assigned.



In [31]:
# Example 1 - working
data = torch.randn(size=[3,5])
data

tensor([[ 1.4416, -0.4378, -2.0714, -0.6321,  1.0958],
        [ 0.0752, -0.0730, -0.1158, -0.1328, -0.2804],
        [ 1.2769, -0.4576,  0.0442,  1.0833,  1.3341]])

In [33]:
abs_data = torch.abs(data)
abs_data

tensor([[1.4416, 0.4378, 2.0714, 0.6321, 1.0958],
        [0.0752, 0.0730, 0.1158, 0.1328, 0.2804],
        [1.2769, 0.4576, 0.0442, 1.0833, 1.3341]])

The absolute value of the input data generated with randn function is assigned to abs_data which has all positive value as expected.

In [35]:
# Example 2 - working
output = torch.abs(torch.tensor([[1,-1,2,-2],[-1,1,-2,2]]))
output

tensor([[1, 1, 2, 2],
        [1, 1, 2, 2]])

We can directly pass the tensor to the abs function and it returns the absolute value of it.

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
output = None
data = torch.tensor([1+1j,-1-1j])
torch.abs(input=data, out=output)


RuntimeError: ignored

It doesn't work with complex numbers.

This function is used to calculate loss function and optimization.

## Function 5 - torch.tensor: add

This function add a scalar to tensor and returns new tensor as an output. The scalar to be added should be compatible with the tensor datatype.

torch.add(input, other, out=None)



In [43]:
# Example 1 - working
value = 555.
data = torch.randn(size=(3,4))
data


tensor([[-3.8150e-01, -1.1130e+00,  1.0138e-03,  1.2307e+00],
        [ 1.6863e-01,  3.6077e-01,  6.4210e-01,  1.0898e+00],
        [-5.3647e-02,  3.1737e-01, -7.6043e-01, -1.6749e-03]])

In [44]:
torch.add(data,other=value)


tensor([[554.6185, 553.8870, 555.0010, 556.2307],
        [555.1686, 555.3608, 555.6421, 556.0898],
        [554.9464, 555.3174, 554.2396, 554.9984]])

The scalar value of type float is added to each element of the tensor input data.


In [45]:
# Example 2 - working
value = 555
data = torch.randn(size=(3,4))
data


tensor([[-1.2101, -0.4521,  0.4845,  1.6008],
        [-0.4633, -1.2183,  0.6812, -0.4122],
        [-0.7107, -0.7804,  0.4641,  0.0239]])

In [47]:
new_data=torch.add(data,other=value, out=new_data)
new_data

tensor([[553.7899, 554.5480, 555.4845, 556.6008],
        [554.5367, 553.7817, 555.6812, 554.5878],
        [554.2893, 554.2196, 555.4641, 555.0239]])

The integer scalar has been added in all the element of the tensor and it has been copied to new output file.

In [49]:
# Example 3 - breaking (to illustrate when it breaks)
value1 = torch.tensor()
data = torch.randn(size=(3,4))
torch.add(data,other=value1, out=None)

TypeError: ignored

This above example fails because the other argument passed should be a scalar value to be added to input but instead it finds tensor datatype which is not acceptable.


This function can be used during optimiation like gradient descent calculation.

## Conclusion

This notebook contains the five pytorch functions that operate on tensors and tried to simplify the functionality with the proper examples where it would work or may throw errors.

There are many more such built-in pytorch functionalities which makes this framework flexible and easier to understand.


## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [0]:
!pip install jovian --upgrade --quiet

In [0]:
import jovian

In [58]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
